function runFinalRFTest(imageName)
% RUNFINALRFTEST
% Final end-to-end RF Signal Classification test.
%
% USER FLOW:
%
%   Run:
%       runFinalRFTest
%
%   A file-selection window opens.
%
%   User selects an RF signal image.
%
%   The system:
%       1. Loads the trained model
%       2. Reads the selected image
%       3. Preprocesses the image
%       4. Runs classification
%       5. Applies UNKNOWN threshold
%       6. Generates Grad-CAM for KNOWN signals
%       7. Opens a polished visual result window
%       8. Saves a text report
%
% OPTIONAL:
%
%   runFinalRFTest("wifi.png")
%
% EXISTING CONNECTIONS PRESERVED:
%
%   rfSignalNet.mat
%   preprocessRFImage.m
%   gradCAM_RFSignal.m
%   unknown_threshold.mat
%   results folder
%
% IMPORTANT:
%
%   UNKNOWN signals do NOT receive Grad-CAM.
%
% Existing Grad-CAM function returns:
%
%   [scoreMap, predictedLabel, confidence]

%% ============================================================
% 1. Project paths
% =============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('          RF SIGNAL CLASSIFICATION - FINAL TEST\n');
fprintf('============================================================\n\n');

projectRoot = fileparts(fileparts(mfilename('fullpath')));

functionsFolder = fullfile(projectRoot, 'functions');
modelsFolder    = fullfile(projectRoot, 'models');
resultsFolder   = fullfile(projectRoot, 'results');
testFolder      = fullfile(projectRoot, 'Test');

% Add project folders to MATLAB path
if isfolder(functionsFolder)
    addpath(functionsFolder);
end

if isfolder(projectRoot)
    addpath(genpath(projectRoot));
end

% Create results folder if necessary
if ~isfolder(resultsFolder)
    mkdir(resultsFolder);
end

fprintf('Project root:\n%s\n\n', projectRoot);

%% ============================================================
% 2. Select test image
% =============================================================

if nargin < 1 || isempty(imageName)

    fprintf('Opening test image selection window...\n\n');

    [selectedFile, selectedFolder] = uigetfile( ...
        { ...
        '*.png;*.jpg;*.jpeg;*.bmp;*.tif;*.tiff', ...
        'RF Signal Images (*.png, *.jpg, *.jpeg, *.bmp, *.tif, *.tiff)'; ...
        '*.*', ...
        'All Files (*.*)' ...
        }, ...
        'Select RF Signal Test Image', ...
        testFolder);

    % User cancelled
    if isequal(selectedFile, 0)

        fprintf('Image selection cancelled by user.\n');
        fprintf('Final test stopped.\n\n');

        return;

    end

    imagePath = fullfile( ...
        selectedFolder, ...
        selectedFile);

else

    imageName = string(imageName);

    % Full path supplied
    if isfile(imageName)

        imagePath = char(imageName);

    else

        % Search inside Test folder
        imagePath = fullfile( ...
            testFolder, ...
            char(imageName));

    end

end

% Validate selected image
if ~isfile(imagePath)

    error( ...
        'Selected test image does not exist: %s', ...
        imagePath);

end

fprintf( ...
    'Selected test image:\n%s\n\n', ...
    imagePath);

%% ============================================================
% 3. Load trained model
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Loading trained model...\n');
fprintf('------------------------------------------------------------\n\n');

modelPath = fullfile( ...
    modelsFolder, ...
    'rfSignalNet.mat');

if ~isfile(modelPath)

    error( ...
        'Trained model not found: %s', ...
        modelPath);

end

data = load( ...
    modelPath, ...
    'net');

if ~isfield(data, 'net')

    error( ...
        'The model file does not contain a variable named "net".');

end

net = data.net;

fprintf('Model loaded successfully.\n\n');

fprintf('Network input size: ');
disp(net.Layers(1).InputSize);

%% ============================================================
% 4. Load UNKNOWN threshold
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Loading UNKNOWN threshold...\n');
fprintf('------------------------------------------------------------\n\n');

thresholdPath = fullfile( ...
    resultsFolder, ...
    'unknown_threshold.mat');

if isfile(thresholdPath)

    thresholdData = load( ...
        thresholdPath, ...
        'threshold');

    if ~isfield( ...
            thresholdData, ...
            'threshold')

        error( ...
            'unknown_threshold.mat does not contain "threshold".');

    end

    unknownThreshold = thresholdData.threshold;

else

    % Calibrated fallback threshold
    unknownThreshold = 0.9305;

    fprintf( ...
        'Warning: unknown_threshold.mat not found.\n');

    fprintf( ...
        'Using fallback threshold: %.2f%%\n\n', ...
        unknownThreshold * 100);

end

fprintf( ...
    'UNKNOWN threshold: %.2f%%\n\n', ...
    unknownThreshold * 100);

%% ============================================================
% 5. Read image
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Reading test image...\n');
fprintf('------------------------------------------------------------\n\n');

originalImage = imread(imagePath);

fprintf('Image loaded successfully.\n');

fprintf('Original image size: ');
disp(size(originalImage));

%% ============================================================
% 6. Preprocess image
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Preprocessing image...\n');
fprintf('------------------------------------------------------------\n\n');

inputImage = preprocessRFImage(originalImage);

fprintf('Preprocessing completed successfully.\n');

fprintf('Network input size: ');
disp(size(inputImage));

fprintf( ...
    'Input data type: %s\n', ...
    class(inputImage));

fprintf( ...
    'Input minimum value: %.4f\n', ...
    min(inputImage(:)));

fprintf( ...
    'Input maximum value: %.4f\n\n', ...
    max(inputImage(:)));

%% ============================================================
% 7. Neural network prediction
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Running neural network prediction...\n');
fprintf('------------------------------------------------------------\n\n');

[networkLabel, scores] = classify( ...
    net, ...
    inputImage);

% Convert scores to numeric
scores = double(scores);

% Highest probability
networkConfidence = max(scores);

% Convert categorical label to string
networkLabelString = string(networkLabel);

fprintf( ...
    'Neural network prediction: %s\n', ...
    networkLabelString);

fprintf( ...
    'Neural network confidence: %.2f%%\n\n', ...
    networkConfidence * 100);

%% ============================================================
% 8. Apply UNKNOWN threshold
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Applying UNKNOWN detection...\n');
fprintf('------------------------------------------------------------\n\n');

if networkConfidence < unknownThreshold

    finalDecision = "UNKNOWN";

else

    finalDecision = networkLabelString;

end

fprintf( ...
    'Neural network prediction : %s\n', ...
    networkLabelString);

fprintf( ...
    'Model confidence          : %.2f%%\n', ...
    networkConfidence * 100);

fprintf( ...
    'UNKNOWN threshold         : %.2f%%\n', ...
    unknownThreshold * 100);

fprintf( ...
    'Final system decision     : %s\n\n', ...
    finalDecision);

%% ============================================================
% 9. Class probabilities
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Class probabilities\n');
fprintf('------------------------------------------------------------\n\n');

classNames = string( ...
    net.Layers(end).Classes);

for i = 1:numel(classNames)

    fprintf( ...
        '%-22s : %7.2f%%\n', ...
        classNames(i), ...
        scores(i) * 100);

end

fprintf('\n');

%% ============================================================
% 10. Top predictions
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Top predictions\n');
fprintf('------------------------------------------------------------\n\n');

[sortedScores, sortedIndices] = ...
    sort(scores, 'descend');

topCount = min(3, numel(sortedScores));

topPredictionNames = strings( ...
    topCount, ...
    1);

topPredictionScores = zeros( ...
    topCount, ...
    1);

for i = 1:topCount

    topPredictionNames(i) = ...
        classNames(sortedIndices(i));

    topPredictionScores(i) = ...
        sortedScores(i);

    fprintf( ...
        '%d. %-20s : %.2f%%\n', ...
        i, ...
        topPredictionNames(i), ...
        topPredictionScores(i) * 100);

end

fprintf('\n');

%% ============================================================
% 11. UNKNOWN explanation
% =============================================================

if finalDecision == "UNKNOWN"

    fprintf('------------------------------------------------------------\n');
    fprintf('UNKNOWN SIGNAL DETECTED\n');
    fprintf('------------------------------------------------------------\n\n');

    fprintf( ...
        'The neural network selected: %s\n', ...
        networkLabelString);

    fprintf( ...
        'Model confidence: %.2f%%\n', ...
        networkConfidence * 100);

    fprintf( ...
        'Required threshold: %.2f%%\n', ...
        unknownThreshold * 100);

    fprintf('\n');

    fprintf( ...
        ['Because the confidence is below the calibrated ', ...
         'threshold, the final system decision is UNKNOWN.\n']);

    fprintf('\n');

    fprintf( ...
        ['Grad-CAM will NOT be generated because the ', ...
         'signal was rejected as UNKNOWN.\n']);

    fprintf('\n');

end

%% ============================================================
% 12. Grad-CAM variables
% =============================================================

heatmapPath = "";
overlayPath = "";

scoreMap = [];

heatmapImage = [];
overlayImage = [];

gradCAMLabel = "";
gradCAMConfidence = 0;

%% ============================================================
% 13. Generate Grad-CAM only for KNOWN signal
% =============================================================

if finalDecision ~= "UNKNOWN"

    fprintf('------------------------------------------------------------\n');
    fprintf('Generating Grad-CAM explanation...\n');
    fprintf('------------------------------------------------------------\n\n');

    try

        % IMPORTANT:
        %
        % Existing gradCAM_RFSignal returns:
        %
        %   1. scoreMap
        %   2. predictedLabel
        %   3. confidence

        [scoreMap, gradCAMLabel, gradCAMConfidence] = ...
            gradCAM_RFSignal( ...
                imagePath, ...
                net);

        % Make sure score map is numeric
        scoreMap = double(scoreMap);

        if isempty(scoreMap)

            error( ...
                'Grad-CAM returned an empty score map.');

        end

        % Normalize score map
        minValue = min(scoreMap(:));
        maxValue = max(scoreMap(:));

        if maxValue > minValue

            scoreMap = ...
                (scoreMap - minValue) ./ ...
                (maxValue - minValue);

        else

            scoreMap = zeros( ...
                size(scoreMap));

        end

        % Original image dimensions
        imageHeight = size( ...
            originalImage, ...
            1);

        imageWidth = size( ...
            originalImage, ...
            2);

        % Resize score map
        resizedScoreMap = imresize( ...
            scoreMap, ...
            [imageHeight imageWidth]);

        % Convert score map to RGB heatmap
        heatmapRGB = ind2rgb( ...
            uint8(resizedScoreMap * 255), ...
            jet(256));

        % Make original image RGB
        if ndims(originalImage) == 2

            originalRGB = cat( ...
                3, ...
                originalImage, ...
                originalImage, ...
                originalImage);

        elseif size(originalImage,3) == 4

            originalRGB = ...
                originalImage(:,:,1:3);

        else

            originalRGB = ...
                originalImage;

        end

        % Convert image to [0,1]
        originalRGB = im2single( ...
            originalRGB);

        % Create Grad-CAM overlay
        overlayImage = ...
            0.55 * originalRGB + ...
            0.45 * heatmapRGB;

        % Keep valid range
        overlayImage = ...
            min(max(overlayImage,0),1);

        % File names
        [~, imageBaseName, ~] = ...
            fileparts(imagePath);

        heatmapPath = fullfile( ...
            resultsFolder, ...
            sprintf( ...
                'gradcam_%s_heatmap.png', ...
                imageBaseName));

        overlayPath = fullfile( ...
            resultsFolder, ...
            sprintf( ...
                'gradcam_%s_overlay.png', ...
                imageBaseName));

        % Save files
        imwrite( ...
            heatmapRGB, ...
            heatmapPath);

        imwrite( ...
            overlayImage, ...
            overlayPath);

        fprintf( ...
            'Grad-CAM generated successfully.\n');

        fprintf( ...
            'Heatmap size: %d x %d\n\n', ...
            size(scoreMap,1), ...
            size(scoreMap,2));

        fprintf( ...
            'Grad-CAM heatmap saved:\n%s\n\n', ...
            heatmapPath);

        fprintf( ...
            'Grad-CAM overlay saved:\n%s\n\n', ...
            overlayPath);

    catch ME

        fprintf('\n');

        fprintf( ...
            'WARNING: Grad-CAM generation failed.\n');

        fprintf( ...
            'Reason: %s\n\n', ...
            ME.message);

        scoreMap = [];

        heatmapImage = [];
        overlayImage = [];

        heatmapPath = "";
        overlayPath = "";

    end

else

    fprintf('------------------------------------------------------------\n');
    fprintf('Grad-CAM skipped\n');
    fprintf('------------------------------------------------------------\n\n');

    fprintf( ...
        ['Final decision is UNKNOWN, so Grad-CAM is ', ...
         'intentionally not generated.\n\n']);

end

%% ============================================================
% 14. Save final text report
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Saving final report...\n');
fprintf('------------------------------------------------------------\n\n');

[~, imageBaseName, ~] = ...
    fileparts(imagePath);

reportPath = fullfile( ...
    resultsFolder, ...
    sprintf( ...
        'final_test_%s.txt', ...
        imageBaseName));

reportFile = fopen( ...
    reportPath, ...
    'w');

if reportFile == -1

    error( ...
        'Unable to create report file: %s', ...
        reportPath);

end

fprintf( ...
    reportFile, ...
    '============================================================\n');

fprintf( ...
    reportFile, ...
    '             RF SIGNAL CLASSIFICATION REPORT\n');

fprintf( ...
    reportFile, ...
    '============================================================\n\n');

fprintf( ...
    reportFile, ...
    'Test image                 : %s\n', ...
    imagePath);

fprintf( ...
    reportFile, ...
    'Neural network prediction  : %s\n', ...
    networkLabelString);

fprintf( ...
    reportFile, ...
    'Model confidence           : %.2f%%\n', ...
    networkConfidence * 100);

fprintf( ...
    reportFile, ...
    'UNKNOWN threshold          : %.2f%%\n', ...
    unknownThreshold * 100);

fprintf( ...
    reportFile, ...
    'Final prediction           : %s\n', ...
    finalDecision);

fprintf(reportFile, '\n');

if finalDecision == "UNKNOWN"

    fprintf( ...
        reportFile, ...
        'Decision                  : UNKNOWN SIGNAL\n');

    fprintf( ...
        reportFile, ...
        'Grad-CAM                  : NOT GENERATED\n');

else

    fprintf( ...
        reportFile, ...
        'Decision                  : KNOWN SIGNAL\n');

    if strlength(heatmapPath) > 0

        fprintf( ...
            reportFile, ...
            'Grad-CAM                  : GENERATED\n');

        fprintf( ...
            reportFile, ...
            'Heatmap                   : %s\n', ...
            heatmapPath);

        fprintf( ...
            reportFile, ...
            'Overlay                   : %s\n', ...
            overlayPath);

    else

        fprintf( ...
            reportFile, ...
            'Grad-CAM                  : FAILED\n');

    end

end

fprintf(reportFile, '\n');

fprintf( ...
    reportFile, ...
    '------------------------------------------------------------\n');

fprintf( ...
    reportFile, ...
    'CLASS PROBABILITIES\n');

fprintf( ...
    reportFile, ...
    '------------------------------------------------------------\n\n');

for i = 1:numel(classNames)

    fprintf( ...
        reportFile, ...
        '%-22s : %7.2f%%\n', ...
        classNames(i), ...
        scores(i) * 100);

end

fprintf(reportFile, '\n');

fprintf( ...
    reportFile, ...
    '============================================================\n');

fprintf( ...
    reportFile, ...
    'END OF REPORT\n');

fprintf( ...
    reportFile, ...
    '============================================================\n');

fclose(reportFile);

fprintf( ...
    'Final report saved successfully.\n\n');

fprintf( ...
    'Report:\n%s\n\n', ...
    reportPath);

%% ============================================================
% 15. Create polished visual result window
% =============================================================

fprintf('------------------------------------------------------------\n');
fprintf('Opening visual result window...\n');
fprintf('------------------------------------------------------------\n\n');

try

    %% --------------------------------------------------------
    % Figure
    % ---------------------------------------------------------

    resultFigure = figure( ...
        'Name', ...
        'RF Signal Classification Result', ...
        'NumberTitle', ...
        'off', ...
        'Color', ...
        'white', ...
        'MenuBar', ...
        'none', ...
        'ToolBar', ...
        'none', ...
        'Position', ...
        [80 60 1450 850]);

    %% --------------------------------------------------------
    % Main title
    % ---------------------------------------------------------

    annotation( ...
        resultFigure, ...
        'textbox', ...
        [0.02 0.935 0.96 0.055], ...
        'String', ...
        'RF SIGNAL CLASSIFICATION RESULT', ...
        'HorizontalAlignment', ...
        'center', ...
        'VerticalAlignment', ...
        'middle', ...
        'FontSize', ...
        20, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        [0.08 0.08 0.08], ...
        'EdgeColor', ...
        'none');

    %% --------------------------------------------------------
    % Test image axes
    % ---------------------------------------------------------

    ax1 = axes( ...
        'Parent', ...
        resultFigure, ...
        'Position', ...
        [0.035 0.455 0.29 0.43]);

    imshow( ...
        originalImage, ...
        'Parent', ...
        ax1);

    title( ...
        ax1, ...
        'TEST IMAGE', ...
        'FontSize', ...
        15, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        [0.08 0.08 0.08]);

    %% --------------------------------------------------------
    % Grad-CAM axes
    % ---------------------------------------------------------

    ax2 = axes( ...
        'Parent', ...
        resultFigure, ...
        'Position', ...
        [0.355 0.455 0.29 0.43]);

    if finalDecision ~= "UNKNOWN" && ...
            ~isempty(overlayImage)

        imshow( ...
            overlayImage, ...
            'Parent', ...
            ax2);

        title( ...
            ax2, ...
            sprintf( ...
                'GRAD-CAM - %s', ...
                upper(char(finalDecision))), ...
            'FontSize', ...
            15, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            [0.08 0.08 0.08]);

    else

        imshow( ...
            originalImage, ...
            'Parent', ...
            ax2);

        title( ...
            ax2, ...
            'GRAD-CAM NOT GENERATED', ...
            'FontSize', ...
            15, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            [0.08 0.08 0.08]);

        text( ...
            ax2, ...
            0.5, ...
            0.5, ...
            'UNKNOWN SIGNAL', ...
            'Units', ...
            'normalized', ...
            'HorizontalAlignment', ...
            'center', ...
            'FontSize', ...
            18, ...
            'FontWeight', ...
            'bold', ...
            'Color', ...
            'white', ...
            'BackgroundColor', ...
            'black');

    end

    %% --------------------------------------------------------
    % Confidence chart
    % ---------------------------------------------------------

    ax3 = axes( ...
        'Parent', ...
        resultFigure, ...
        'Position', ...
        [0.675 0.455 0.29 0.43]);

    % All class probabilities
    bar( ...
        ax3, ...
        1:numel(scores), ...
        scores, ...
        0.65, ...
        'FaceColor', ...
        [0.35 0.55 0.80], ...
        'EdgeColor', ...
        [0.15 0.25 0.40]);

    hold(ax3, 'on');

    % Highlight neural network prediction
    [~, predictedIndex] = ...
        max(scores);

    bar( ...
        ax3, ...
        predictedIndex, ...
        scores(predictedIndex), ...
        0.65, ...
        'FaceColor', ...
        [0.90 0.50 0.15], ...
        'EdgeColor', ...
        [0.55 0.25 0.05]);

    % UNKNOWN threshold line
    yline( ...
        ax3, ...
        unknownThreshold, ...
        '--', ...
        'UNKNOWN Threshold', ...
        'LineWidth', ...
        1.5, ...
        'Color', ...
        [0.70 0.15 0.15]);

    hold(ax3, 'off');

    title( ...
        ax3, ...
        'CLASS CONFIDENCE', ...
        'FontSize', ...
        15, ...
        'FontWeight', ...
        'bold', ...
        'Color', ...
        [0.08 0.08 0.08]);

    xlabel( ...
        ax3, ...
        'RF CLASS', ...
        'FontSize', ...
        11, ...
        'FontWeight', ...
        'bold');

    ylabel( ...
        ax3, ...
        'CONFIDENCE', ...
        'FontSize', ...
        11, ...
        'FontWeight', ...
        'bold');

    ylim( ...
        ax3, ...
        [0 1.05]);

    xlim( ...
        ax3, ...
        [0.5 numel(classNames) + 0.5]);

    xticks( ...
        ax3, ...
        1:numel(classNames));

    xticklabels( ...
        ax3, ...
        classNames);

    xtickangle( ...
        ax3, ...
        40);

    grid( ...
        ax3, ...
        'on');

    set( ...
        ax3, ...
        'FontSize', ...
        10, ...
        'XColor', ...
        [0.10 0.10 0.10], ...
        'YColor', ...
        [0.10 0.10 0.10], ...
        'Color', ...
        'white');

    %% ========================================================
    % Bottom information panel
    % =========================================================

    % Create panel
    infoPanel = uipanel( ...
        'Parent', ...
        resultFigure, ...
        'Position', ...
        [0.035 0.055 0.93 0.34], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96], ...
        'BorderType', ...
        'line', ...
        'HighlightColor', ...
        [0.70 0.70 0.70]);

    %% --------------------------------------------------------
    % Panel title
    % ---------------------------------------------------------

    uicontrol( ...
        'Parent', ...
        infoPanel, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.02 0.80 0.96 0.16], ...
        'String', ...
        'FINAL SYSTEM DECISION', ...
        'FontSize', ...
        14, ...
        'FontWeight', ...
        'bold', ...
        'ForegroundColor', ...
        [0.10 0.10 0.10], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96]);

    %% --------------------------------------------------------
    % Final prediction
    % ---------------------------------------------------------

    uicontrol( ...
        'Parent', ...
        infoPanel, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.02 0.47 0.96 0.30], ...
        'String', ...
        upper(char(finalDecision)), ...
        'FontSize', ...
        27, ...
        'FontWeight', ...
        'bold', ...
        'ForegroundColor', ...
        [0.05 0.30 0.55], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96]);

    %% --------------------------------------------------------
    % Network prediction
    % ---------------------------------------------------------

    networkText = sprintf( ...
        'Neural Network: %s', ...
        upper(char(networkLabelString)));

    uicontrol( ...
        'Parent', ...
        infoPanel, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.03 0.25 0.30 0.18], ...
        'String', ...
        networkText, ...
        'FontSize', ...
        12, ...
        'FontWeight', ...
        'bold', ...
        'ForegroundColor', ...
        [0.15 0.15 0.15], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96]);

    %% --------------------------------------------------------
    % Confidence
    % ---------------------------------------------------------

    confidenceText = sprintf( ...
        'Confidence: %.2f%%', ...
        networkConfidence * 100);

    uicontrol( ...
        'Parent', ...
        infoPanel, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.35 0.25 0.25 0.18], ...
        'String', ...
        confidenceText, ...
        'FontSize', ...
        12, ...
        'FontWeight', ...
        'bold', ...
        'ForegroundColor', ...
        [0.15 0.15 0.15], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96]);

    %% --------------------------------------------------------
    % Threshold
    % ---------------------------------------------------------

    thresholdText = sprintf( ...
        'UNKNOWN Threshold: %.2f%%', ...
        unknownThreshold * 100);

    uicontrol( ...
        'Parent', ...
        infoPanel, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.62 0.25 0.35 0.18], ...
        'String', ...
        thresholdText, ...
        'FontSize', ...
        12, ...
        'FontWeight', ...
        'bold', ...
        'ForegroundColor', ...
        [0.15 0.15 0.15], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96]);

    %% --------------------------------------------------------
    % Status line
    % ---------------------------------------------------------

    if finalDecision == "UNKNOWN"

        statusText = ...
            'UNKNOWN SIGNAL  |  Grad-CAM NOT GENERATED';

    else

        if strlength(heatmapPath) > 0

            statusText = ...
                'KNOWN SIGNAL  |  Grad-CAM GENERATED';

        else

            statusText = ...
                'KNOWN SIGNAL  |  Grad-CAM FAILED';

        end

    end

    uicontrol( ...
        'Parent', ...
        infoPanel, ...
        'Style', ...
        'text', ...
        'Units', ...
        'normalized', ...
        'Position', ...
        [0.02 0.04 0.96 0.14], ...
        'String', ...
        statusText, ...
        'FontSize', ...
        11, ...
        'FontWeight', ...
        'bold', ...
        'ForegroundColor', ...
        [0.25 0.25 0.25], ...
        'BackgroundColor', ...
        [0.96 0.96 0.96]);

    %% --------------------------------------------------------
    % Draw window
    % ---------------------------------------------------------

    drawnow;

    fprintf( ...
        'Visual result window opened successfully.\n\n');

catch ME

    fprintf('\n');

    fprintf( ...
        'WARNING: Visual result window could not be opened.\n');

    fprintf( ...
        'Reason: %s\n\n', ...
        ME.message);

end

%% ============================================================
% 16. Final console summary
% =============================================================

fprintf('\n');
fprintf('============================================================\n');
fprintf('                 FINAL TEST COMPLETE\n');
fprintf('============================================================\n\n');

if finalDecision == "UNKNOWN"

    fprintf( ...
        'Neural network prediction : %s\n', ...
        networkLabelString);

    fprintf( ...
        'Model confidence          : %.2f%%\n', ...
        networkConfidence * 100);

    fprintf( ...
        'UNKNOWN threshold         : %.2f%%\n', ...
        unknownThreshold * 100);

    fprintf( ...
        'Final prediction          : UNKNOWN\n');

    fprintf('\n');

    fprintf( ...
        'Decision                  : UNKNOWN SIGNAL\n');

    fprintf( ...
        'Grad-CAM                  : NOT GENERATED\n');

else

    fprintf( ...
        'Neural network prediction : %s\n', ...
        networkLabelString);

    fprintf( ...
        'Model confidence          : %.2f%%\n', ...
        networkConfidence * 100);

    fprintf( ...
        'UNKNOWN threshold         : %.2f%%\n', ...
        unknownThreshold * 100);

    fprintf( ...
        'Final prediction          : %s\n', ...
        finalDecision);

    fprintf('\n');

    fprintf( ...
        'Decision                  : KNOWN SIGNAL\n');

    if strlength(heatmapPath) > 0

        fprintf( ...
            'Grad-CAM                  : GENERATED\n');

    else

        fprintf( ...
            'Grad-CAM                  : FAILED\n');

    end

end

fprintf('\n');

fprintf( ...
    'Final report:\n%s\n', ...
    reportPath);

fprintf('\n');

fprintf( ...
    'Results directory:\n%s\n', ...
    resultsFolder);

fprintf('\n');

fprintf( ...
    '============================================================\n\n');

end